[workspace]
members = ["host", "guest", "common"]
resolver = "2"
exclude = ["guest-sp1", "guest-risc0", "guest-jolt", "guest-zisk", "guest-pico"]

[workspace.dependencies]
ere-zkvm-interface = { git = "https://github.com/eth-act/ere.git"}
ere-dockerized = { git = "https://github.com/eth-act/ere.git"}

# utils
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
