[workspace]
members = ["host", "guest", "common", "guest-sp1"]
resolver = "2"

[workspace.dependencies]
ere-zkvm-interface = { git = "https://github.com/eth-act/ere.git"}
ere-dockerized = { git = "https://github.com/eth-act/ere.git"}

# utils
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[patch.crates-io]
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", tag = "patch-2.0.2-sp1-4.0.0" }
k256 = { git = "https://github.com/sp1-patches/elliptic-curves", tag = "patch-k256-13.4-sp1-5.0.0" }
